### ISSUE TITLE
NPM package is not available

### ISSUE THREAD

**Issue by x1unix** [browser-fs/fs-zip#1]
I attempted to install the package via Yarn and found out that package is missing:

```
yarn add @browserfs/fs-zip

➤ YN0027: @browserfs/fs-zip@unknown can't be resolved to a satisfying range
➤ YN0035: The remote server failed to provide the requested resource
➤ YN0035:   Response Code: 404 (Not Found)
➤ YN0035:   Request Method: GET
➤ YN0035:   Request URL: https://registry.yarnpkg.com/@browserfs%2ffs-zip
```

https://www.npmjs.com/package/@browserfs/fs-zip

**Comment by dr-vortex** [comment]
@x1unix,

My apologies, I intended to publish it after finishing the initial programming though got pulled away from the project.

It has now been published on NPM. There are currently no tests so I cannot guarantee the stability, though it should be very similar to before the modularization.

Please create another issue if you encounter a problem.
